spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lemongrab

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update